# Generated by Django 5.1.3 on 2024-11-08 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('HSN_code', models.CharField(max_length=50)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('default_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_rank', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=255)),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='billing_app.client')),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['product_id'],
            },
        ),
    ]
