# Generated by Django 5.1.3 on 2024-11-12 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('category', models.CharField(max_length=50)),
                ('GSTIN', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('sales_rank', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=50)),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.client')),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['customer_id'],
            },
        ),
    ]
