# Generated by Django 5.1.3 on 2024-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_alter_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gstn',
            field=models.CharField(default='URP', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='place_of_supply',
            field=models.CharField(default='Kerala', max_length=15),
        ),
    ]
