# Generated by Django 5.1.3 on 2024-12-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_customerbill_billtaxsplit_billitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('place_of_supply', models.CharField(max_length=255)),
                ('GSTIN', models.CharField(default='NRP', max_length=15)),
                ('is_inactive', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='billing_app.client')),
            ],
            options={
                'db_table': 'Vendor',
                'ordering': ['vendor_id'],
            },
        ),
    ]
